// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGKfHzPA2c9ZiJTaretWYS7-h98ca5MDw',
    appId: '1:290701403463:web:766be1ac53a716af605862',
    messagingSenderId: '290701403463',
    projectId: 'appointment-3930b',
    authDomain: 'appointment-3930b.firebaseapp.com',
    storageBucket: 'appointment-3930b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpVhKJDwfamD2UQ8lJbNjnKDWTvtQr_Z4',
    appId: '1:290701403463:android:44b5f8ced692dab0605862',
    messagingSenderId: '290701403463',
    projectId: 'appointment-3930b',
    storageBucket: 'appointment-3930b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYTP4mJG69DaHCkHwmwdgupOnviVOzvJE',
    appId: '1:290701403463:ios:97128c77e5b95cba605862',
    messagingSenderId: '290701403463',
    projectId: 'appointment-3930b',
    storageBucket: 'appointment-3930b.firebasestorage.app',
    iosBundleId: 'com.example.appointmentMgmtApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYTP4mJG69DaHCkHwmwdgupOnviVOzvJE',
    appId: '1:290701403463:ios:97128c77e5b95cba605862',
    messagingSenderId: '290701403463',
    projectId: 'appointment-3930b',
    storageBucket: 'appointment-3930b.firebasestorage.app',
    iosBundleId: 'com.example.appointmentMgmtApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGKfHzPA2c9ZiJTaretWYS7-h98ca5MDw',
    appId: '1:290701403463:web:bf2b7cf3602f387f605862',
    messagingSenderId: '290701403463',
    projectId: 'appointment-3930b',
    authDomain: 'appointment-3930b.firebaseapp.com',
    storageBucket: 'appointment-3930b.firebasestorage.app',
  );
}
